# Generated by Django 3.1.3 on 2020-11-12 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('dept_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('lect_id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100, null=True)),
                ('firstname', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
                ('phoneno', models.IntegerField(null=True)),
                ('dept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='educrew.dept')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sub_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectInfo',
            fields=[
                ('unq_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lect_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='educrew.lecturer')),
                ('sub_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='educrew.subject')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec', models.IntegerField(null=True)),
                ('day', models.DateField(null=True)),
                ('p1', models.IntegerField(null=True)),
                ('p2', models.IntegerField(null=True)),
                ('p3', models.IntegerField(null=True)),
                ('p4', models.IntegerField(null=True)),
                ('dept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='educrew.dept')),
                ('unq_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='educrew.subjectinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rollno', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100, null=True)),
                ('firstname', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
                ('phoneno', models.IntegerField(null=True)),
                ('year', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True)),
                ('sec', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], null=True)),
                ('dept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='educrew.dept')),
            ],
        ),
        migrations.CreateModel(
            name='LecturerSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec', models.IntegerField(null=True)),
                ('day', models.DateField(null=True)),
                ('p1', models.IntegerField(null=True)),
                ('p2', models.IntegerField(null=True)),
                ('p3', models.IntegerField(null=True)),
                ('p4', models.IntegerField(null=True)),
                ('dept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='educrew.dept')),
                ('unq_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='educrew.subjectinfo')),
            ],
        ),
    ]
