# Generated by Django 3.1.3 on 2020-11-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educrew', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='dept_name',
            field=models.CharField(max_length=40),
        ),
    ]
