# Generated by Django 3.1.3 on 2020-11-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educrew', '0002_auto_20201112_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='dept_name',
            field=models.CharField(max_length=60),
        ),
    ]
