# Generated by Django 3.1.3 on 2020-11-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educrew', '0003_auto_20201112_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentschedule',
            name='day',
            field=models.CharField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=10, null=True),
        ),
    ]
