# Generated by Django 3.1.3 on 2020-11-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educrew', '0006_auto_20201112_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentschedule',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10, null=True),
        ),
    ]
