# Generated by Django 3.1 on 2020-11-13 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educrew', '0009_lecturerschedule_lect_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.AddField(
            model_name='subjectinfo',
            name='dept_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='educrew.dept'),
        ),
        migrations.AddField(
            model_name='subjectinfo',
            name='sec',
            field=models.IntegerField(null=True),
        ),
    ]
