# Generated by Django 3.1 on 2020-11-13 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educrew', '0010_auto_20201113_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturerschedule',
            name='dept_id',
        ),
        migrations.RemoveField(
            model_name='lecturerschedule',
            name='sec',
        ),
    ]
