# Generated by Django 3.1 on 2020-11-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educrew', '0015_auto_20201116_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept',
            name='dept_short',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
