# Generated by Django 3.1 on 2020-11-16 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educrew', '0016_dept_dept_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentschedule',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
                ('sec', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('dept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='educrew.dept')),
            ],
        ),
    ]
