# Generated by Django 3.1 on 2020-11-16 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educrew', '0017_auto_20201116_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='lect_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='educrew.lecturer'),
        ),
    ]
