# Generated by Django 3.1 on 2020-11-16 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educrew', '0018_announcements_lect_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='lect_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='educrew.lecturer'),
        ),
    ]
