# Generated by Django 3.1 on 2020-11-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educrew', '0019_auto_20201116_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='cabin_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
