# Generated by Django 3.1 on 2020-11-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educrew', '0020_lecturer_cabin_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentschedule',
            name='p1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentschedule',
            name='p2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentschedule',
            name='p3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentschedule',
            name='p4',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
