# Generated by Django 3.1 on 2020-11-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educrew', '0021_auto_20201117_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='lect_id',
            field=models.IntegerField(null=True),
        ),
    ]
