# Generated by Django 3.1 on 2020-11-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educrew', '0022_auto_20201117_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='dept_id',
            field=models.IntegerField(null=True),
        ),
    ]
