# Generated by Django 3.1 on 2020-11-17 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educrew', '0024_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 17, 21, 1, 8, 224979), null=True),
        ),
    ]
