# Generated by Django 3.1 on 2020-11-17 15:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('educrew', '0025_auto_20201117_2101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='announcements',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 17, 15, 40, 7, 737264, tzinfo=utc), null=True),
        ),
    ]
