# Generated by Django 3.1 on 2020-11-17 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educrew', '0029_auto_20201117_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcements',
            name='date',
        ),
    ]
