# Generated by Django 3.1 on 2020-11-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educrew', '0030_remove_announcements_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
