# Generated by Django 3.1 on 2020-11-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educrew', '0036_auto_20201118_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, default='profilepic.jpg', null=True, upload_to=''),
        ),
    ]
