# Generated by Django 3.1 on 2020-11-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educrew', '0040_auto_20201118_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, default='profilepic.jpg', null=True, upload_to=''),
        ),
    ]
