# Generated by Django 3.1 on 2020-11-18 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('educrew', '0043_auto_20201118_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='profile_image',
            field=models.ImageField(default='profilepic.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(default='profilepic.jpg', null=True, upload_to=''),
        ),
    ]
