# Generated by Django 3.1 on 2020-11-20 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educrew', '0044_auto_20201119_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_known', models.CharField(blank=True, max_length=500, null=True)),
                ('prog_lang', models.CharField(blank=True, max_length=500, null=True)),
                ('internships', models.CharField(blank=True, max_length=500, null=True)),
                ('projects', models.CharField(blank=True, max_length=500, null=True)),
                ('links', models.CharField(blank=True, max_length=500, null=True)),
                ('sports', models.CharField(blank=True, max_length=500, null=True)),
                ('other', models.CharField(blank=True, max_length=500, null=True)),
                ('rollno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='educrew.student')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_known', models.CharField(blank=True, max_length=500, null=True)),
                ('qual', models.CharField(blank=True, max_length=500, null=True)),
                ('spcltns', models.CharField(blank=True, max_length=500, null=True)),
                ('projects', models.CharField(blank=True, max_length=500, null=True)),
                ('research', models.CharField(blank=True, max_length=500, null=True)),
                ('other', models.CharField(blank=True, max_length=500, null=True)),
                ('lect_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='educrew.lecturer')),
            ],
        ),
    ]
