# Generated by Django 3.1 on 2020-11-22 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educrew', '0046_auto_20201122_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcements',
            old_name='strt_date',
            new_name='start_date',
        ),
    ]
